[package]
name = "cyptopals"
version = "0.1.0"
authors = ["Frank Schmidt <frank.schmidt@codecentric.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hex = "*"
base64 = "*"
